version: '3'

services:
  db:
    image: postgres
    container_name: onboarding-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - pluggy-onboarding
    expose:
      - 5432
    env_file:
      - .env
    ports:
      - ${DB_HOST_PORT}:5432

networks:
  pluggy-onboarding:

volumes:
  postgres-data:
